backend:
  name: github
  branch: master
  repo: ctoogood/johndory


media_folder: ../static/img
public_folder: ../img

collections:
  - name: "Post"
    label: "Post"
    folder: src/posts
    create: true
    slug: '{{slug}}'
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - { label: "Title", name: "title", widget: 'string' }
      - { label: "Slug", name: "slug", widget: 'string' }
      - { label: "Date", name: "date", widget: 'date' }
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}