backend:
  name: github
  branch: master
  repo: ctoogood/johndory

media_library:
  name: cloudinary
  config:
    cloud_name: dhat0b0ey
    api_key: 328191115239953

media_folder: "static/images" 
public_folder: "/images" 

collections:
  - name: "Post"
    label: "Post"
    folder: src/posts
    create: true
    slug: '{{slug}}'
    fields:
      - { label: "Title", name: "title", widget: 'string' }
      - { label: "Slug", name: "slug", widget: 'string' }
      - { label: "Date", name: "date", widget: 'date' }
      - {label: "Featured Image", name: "featuredImage", widget: "file"}
      - {label: "Body", name: "body", widget: "markdown"}